# Generated by Django 3.2 on 2021-12-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, max_length=255)),
                ('imagem', models.ImageField(blank=True, upload_to='imagens/categorias')),
            ],
        ),
    ]
