# Generated by Django 3.2 on 2021-12-29 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='atualizado_em',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Atualizado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='criado_em',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/categorias', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome na Url'),
        ),
    ]
